AlarmRuleExecutor/Models/DataType.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AlarmRuleExecutor.Models
{
    public enum DataType
    {
        [Display(Name="Numeric")]
        Numeric,
        [Display(Name = "Boolean")]
        Boolean
    }
}

AlarmRuleExecutor/Models/ErrorViewModel.cs
using System;

namespace AlarmRuleExecutor.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlarmRuleExecutor/Models/RuleOperation.cs
using System;
namespace AlarmRuleExecutor.Models
{
    public enum RuleOperation
    {
        Equal=1,
        NotEqual,
        Greater,
        GreaterThanOrEqual,
        Less,
        LessThanOrEqual
    }
}

AlarmRuleExecutor/Models/SensorViewModel.cs
using System;
namespace AlarmRuleExecutor.Models
{
    public class SensorViewModel
    {
        public string Id
        {
            get;
            set;
        }
        public string Name
        {
            get;
            set;
        }

        public string Description
        {
            get;
            set;
        }

        public DataType DataType
        {
            get;
            set;
        }
        public string Value
        {
            get;
            set;
        }

    }
}

AlarmRuleExecutor/Models/SlackMessageModel.cs
using System;
namespace AlarmRuleExecutor.Models
{
    public class SlackMessageModel
    {
        public String SensorName
        {
            get;
            set;
        }
        public String SensorValue { get; set; }
        public String ApiUrl { get; set; }
    }
}

AlarmRuleExecutor/Controllers/AlarmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlarmRuleExecutor.Application.Dto;
using AlarmRuleExecutor.Application.Executor;
using Microsoft.AspNetCore.Mvc;

namespace AlarmRuleExecutor.Controllers
{
    [Route("[controller]")]
    public class AlarmController : Controller
    {
        [HttpPost]
        public async Task<IActionResult> Index([FromBody]SensorDto dto,[FromServices]IRuleExecutor executor)
        {
            dto.CreationTime = DateTime.UtcNow;
            var result = await executor.Execute(dto);
            return Ok(result);
        }
    }
}

AlarmRuleExecutor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AlarmRuleExecutor.Models;
using AlarmRuleExecutor.Application.Data;
using AlarmRuleExecutor.Application.Entity;

namespace AlarmRuleExecutor.Controllers
{
    public class HomeController : Controller
    {
        private IElasticSearchManager _manager;
        public HomeController(IElasticSearchManager manager)
        {
            _manager = manager;
        }
        public async Task<IActionResult> Index()
        {
            var criteria = new Dictionary<string, object>();
            criteria.Add("active", true);
            var sensors = await _manager.Search<Sensor>("sensor", "data", criteria);
           

            return View(sensors);                                                         
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AlarmRuleExecutor/Controllers/SensorController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AlarmRuleExecutor.Application.Data;
using AlarmRuleExecutor.Application.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AlarmRuleExecutor.Controllers
{
    public class SensorController : Controller
    {
        private readonly IElasticSearchManager _manager;

        public SensorController(IElasticSearchManager manager)
        {
            _manager = manager;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            var actionTypes = new List<SelectListItem>();
            actionTypes.Add(new SelectListItem(){Text="Web Request",Value="WebRequest"});
            actionTypes.Add(new SelectListItem() { Text = "Email", Value = "Email" });
            ViewBag.ActionTypes = actionTypes;



            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Sensor entity,[FromServices]IElasticSearchManager manager)
        {
            entity.CreateTime = DateTime.UtcNow;
            entity.Id = Guid.NewGuid();
            entity.IsActive = true;
            await manager.AddAsync("sensor","data",entity);
            return RedirectToAction("index", "home");
        }


    }
}

AlarmRuleExecutor/Controllers/SlackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AlarmRuleExecutor.Application.Dto;
using AlarmRuleExecutor.Application.Executor;
using AlarmRuleExecutor.Application.Security;
using AlarmRuleExecutor.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
namespace AlarmRuleExecutor.Controllers
{
    [Route("[controller]")]
    public class SlackController:Controller
    {
        private static HttpClient _client;
        public SlackController()
        {
            if(_client==null)
                _client = new HttpClient();
        }
        [HttpPost]
        [BasicAuthFilter]
        public async Task<IActionResult> Send([FromBody]SlackMessageModel model )
        {
            //string apiurl = "https://hooks.slack.com/services/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";
            var payload = new
            {
                text = $"{model.SensorName} has sent the value:{model.SensorValue}",
            };
            await _client.PostAsync(model.ApiUrl, new StringContent(JsonConvert.SerializeObject(payload), Encoding.UTF8, "application/json"));
            return Ok();
        }
    }
}

AlarmRuleExecutor/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AlarmRuleExecutor/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AlarmRuleExecutor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using AlarmRuleExecutor.Application.Entity
@using AlarmRuleExecutor.Models
@model List<Sensor>
<div class="row" style="margin-top:20px">
    <div class="col-md-12">
        <a href="@Url.Action("create","sensor")" class="btn btn-primary">Add Sensor</a> 
    </div>

</div>
<hr />
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Sensors</h4>
    </div>
    <div class="panel-body" style="max-height:500px; overflow-y:auto">
        <div class="row">
        @foreach(var sensor in Model){
            <div class="col-md-4">
                <div class="sensor-wrapper">
                   <table class="table table-sm table-bordered">
                        <tr class="danger">
                            <th class="primary">Sensor Id</th><td> @sensor.Id</td>
                        </tr>
                        <tr class="warning">
                            <th class="primary">Sensor Name</th><td> @sensor.Name</td>
                        </tr>
                         <tr class="success">
                            <th class="primary">Sensor Description</th><td> @sensor.Description</td>
                        </tr>
                          <tr class="danger">
                            <th class="primary">Sensor Data Type</th><td> @Enum.Parse(typeof(DataType),sensor.Datatype.ToString())</td>
                        </tr>
                           <tr class="warning">
                            <th class="primary">Rule Count</th><td> @sensor.Rules.Count</td>
                        </tr>
                         <tr class="info">
                            <td colspan="2" class="primary text-right">
                                <a class="btn btn-default btn-sm" onclick="Sensor.openSimulationPopup('@sensor.Id')">Simulate</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        }
        </div>
    </div>
    <div class="panel-footer">
        Total: @Model.Count
    </div>
</div>

Save changes
<div id="sensor-simulator-popup" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Sensor Simulator</h4>
      </div>
      <div class="modal-body">
            <div class="form-group">
                <label class="control-label">Value:</label>
                <input type="text" class="form-control" id="SensorSimulationValue" />
                <input type="hidden" id="SimulationSensorId" />
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="Sensor.sendSimulationValue()">Send</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

AlarmRuleExecutor/Views/Sensor/Create.cshtml
@{
    ViewBag.Title="Sensor Create";
}
@using AlarmRuleExecutor.Models
@model SensorViewModel
<h3>@ViewBag.Title</h3>
@section Header{
    <link href="/css/json-forms/brutusin-json-forms.css" rel="stylesheet"/>
    <link href="/css/bootstrap-select.css" rel="stylesheet"/>
    <link href="/css/treema.css" rel="stylesheet"/>
}



<form method="post" id="sensor-create-form" action="@Url.Action("Create","Sensor")" >

<div class="panel panel-primary">
<div class="panel-heading">
<h4 class="panle-title">Sensor</h4>
    </div>
   <div class="panel-body">

  
    <div class="row">
   
    <div class="col-md-6">
         <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" class="form-control col-md-4" asp-for="Name"/>
    </div>
    </div>
     <div class="col-md-6">
         <div class="form-group">
        <label asp-for="Description" class="control-label">Description</label>
        <textarea type="text" class="form-control" asp-for="Description"></textarea>
    </div>
      </div>
     <div class="col-md-6">
         <div class="form-group">
        <label asp-for="DataType" class="control-label">Data Type</label>
       <select asp-for="DataType" class="form-control" asp-items="@Html.GetEnumSelectList<DataType>()"></select>
    </div>
       
     </div>
       <div class="col-md-6">
         <div class="form-group">
        <label asp-for="Value" class="control-label">Value</label>
        <input type="text" class="form-control" asp-for="Value"/>
    </div>      
     </div>
    </div>
    <div class="clear-fix"></div>

    </div>
      </div>

      <div  class="panel panel-warning">
        <div class="panel-heading">
            <h4 class="panel-title">Rules<a data-toggle="modal" data-target="#rule-modal" style="margin-top:-6px;" class="btn btn-sm pull-right"><i class="glyphicon glyphicon-plus"></i></a></h4> 

        </div>
        <div class="panel-body" id="rules">
            <table class="table table-stripped table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Operation</th>
                        <th>Value</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>  
        </div>
    </div>

    <div class="col-md-12"> 
    <button class="btn btn-primary pull-right"><i class="glyphicon glyphicon-floppy-disk"></i> &nbsp; Save</button>
    </div>
    <div class="clear-fix" ></div>



    
</form>
<div>
</div>

<div id="rule-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Rule</h4>
      </div>
      <div class="modal-body">
           <div class="form-group">
                <label for="rule-name" class="control-lable">Rule Name</label>
                <input type="text" name="rule-name" id="rule-name" class="form-control" />
           </div>
           <div class="form-group">
                <label for="rule-name" class="control-lable">Operation</label>
                <select name="rule-operation" id="rule-operation" class="form-control" asp-items="@Html.GetEnumSelectList<RuleOperation>()"></select>
           </div>
            <div class="form-group">
                <label for="rule-value" class="control-lable">Value</label>
                <input type="text" name="rule-value" id="rule-value" class="form-control" />
           </div>
                
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="Sensor.addRule();">Add</button>
      </div>
    </div>

  </div>
</div>

<div id="action-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Action</h4>
      </div>
      <div class="modal-body">
        <div class="row">
    <div class="col-md-12">
        <section>
            <div>
                <div>
                        <input type="hidden" id="action-ruleId" name="action-ruleId" />                
                        <div class="form-group">
                            @Html.Label("ActionType","Action Type", new { @class = "col-md-3 control-label" })
                            @Html.DropDownList("ActionType", ViewBag.ActionTypes as IEnumerable<SelectListItem>, new { @class = "form-control", onchange = "Action.actionTypeChange()" })
                        </div>
                        <div class="form-group">
                            @Html.Label("Name","Action Name", new { @class = "col-md-3 control-label" })
                            @Html.TextBox("ActionName","",  new { @class = "form-control"  })
                        </div>
                        <div class="clearfix"></div>
                        <div id="KeywordsBtnWrap" class="form-group hidden">
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Ekle <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a onclick="Action.addContent('[ActionDate]')">Eylem Tarihi</a>
                                    </li>
                                    <li>
                                        <a onclick="Action.addContent('[SensorName]')">Sensör Adı</a>
                                    </li>
                                    <li>
                                        <a onclick="Action.addContent('[SensorValue]')">Sensör Değeri</a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div id="ContentWrap" class="form-group">
                            @Html.Label("Content", "", new { @class = " control-label" })                 
                            @Html.TextArea("Content","", new { @class = "form-control", rows = "4" })
                        </div>
                        <div id="SubjectWrap" class="form-group hidden">
                            @Html.Label("Subject","Subject", new { @class = " control-label" })
                            @Html.TextBox("Subject","", new { @class = "form-control" })
                        </div>
                         <div id="ToWrap" class="form-group hidden">
                            @Html.Label("To","To", new { @class = " control-label" })
                            @Html.TextBox("To","", new { @class = "form-control" })
                        </div>
                                    
                        <div id="WebRequestWrap" class="hidden">
                            <div class="form-group">
                                <label class="control-label">Method</label>
                                <select name="Method" class="form-control">
                                    <option value="Get">GET</option>
                                    <option value="Post">POST</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Url</label>
                                <input type="text" class="form-control" name="Url" />
                            </div>
                            <div class="clearfix"></div>

                            <div id="SecurityWrap" class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Security</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="control-label">Type</label>
                                        <select name="Type" class="form-control">
                                            <option>None</option>
                                            <option value="Basic">Basic</option>
                                        </select>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="form-group">
                                        <label class="control-label">Username</label>
                                        <input type="text" class="form-control" name="Username" />
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Password</label>
                                        <input type="password" class="form-control" name="Password" />
                                    </div>

                                </div>
                            </div>


                            <div id="HeadersWrap" class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        Headers <a onclick="Action.addHeader()"  style="margin-top:-6px;" class="btn btn-sm pull-right"><i class="glyphicon glyphicon-plus"></i>
                                        </a>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div id="row-0">
                                        <div class="form-group col-md-6">
                                            <label class="control-label">Name</label>
                                            <input type="text" name="headername[0]" class="header-name form-control" />
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label class="control-label">Value</label>
                                            <input type="text" name="headervalue[0]" class="header-value form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-md-6 mt-10">
                                <label class="control-label">Body</label>
                                <div class="Body"></div>
                            </div>

                        </div>    
                 
                </div>
            </div>
        </section>
    </div>
</div>
                
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="Action.beforeSave();">Add</button>
      </div>
    </div>

  </div>
</div>



@section Scripts{
    <script src="/lib/markdown.js"></script>
    <script src="/lib/bootstrap-select.min.js"></script>
    <script src="/lib/tinymce/js/tinymce/tinymce.min.js"></script>
    <script src="/lib/json-forms/brutusin-json-forms.js"></script>
    <script src="/lib/json-forms/brutusin-json-forms-bootstrap.js"></script>
    <script src="/lib/tv4.min.js" type="text/javascript"></script>
    <script src="/lib/treema.js" type="text/javascript"></script>
    <script type="text/javascript">
       var treema;
        $(document).ready(function() {
            var options = { schema:{ "additionalProperties": true,
                "type": "object",}, data:{} };
            var el = $(".Body");
            treema = el.treema(options);
            treema.build();
        });
    </script>
}

AlarmRuleExecutor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlarmRuleExecutor</title>
    @RenderSection("Header", required: false)
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AlarmRuleExecutor</a>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - AlarmRuleExecutor</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>